services:
  vrising:
    restart: unless-stopped
    container_name: vrising-server-mods
    image: fork
    network_mode: bridge
    environment:
      - ENABLE_MODS=1
    volumes:
      - '/home/maxime/vrising-2/server:/mnt/vrising/server'
      - '/home/maxime/vrising-2/data:/mnt/vrising/persistentdata'
      - '/home/maxime/vrising-2/mods:/mnt/vrising/mods'
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
